### PR TITLE
add dumb-init to image

### PR DESCRIPTION
**Pull request by kadel**
requires https://github.com/redhat-developer/odo/pull/1112 to work

see https://github.com/redhat-developer/odo/pull/1112 and https://github.com/redhat-developer/odo/issues/1076 for more info

### CODE REVIEW

**Review by surajnarwade — APPROVED** [review]
LGTM :tada:

**Review by geoand — APPROVED** [review]
Works like a charm :)

**Review by anmolbabu — APPROVED** [review]
LGTM and works for me

**Comment by geoand** [comment]
Let's get this merged then so the tests in https://github.com/redhat-developer/odo/pull/1112 can pass

**Comment by anmolbabu** [comment]
Merging based on above acks

**Comment by anmolbabu** [comment]
> Let's get this merged then so the tests in [redhat-developer/odo#1112](https://github.com/redhat-developer/odo/pull/1112) can pass

I think we'll need to push out this as a release also for the odo PR to use this as version 0.5.0

**Pull request merged**
