### PR TITLE
moved from redhat-developer/odo to openshift/odo

### PR DESCRIPTION
**Pull request by kadel**
- replaces redhat-developer/odo reference with openshift/odo
- fix and add tests. Integrations tests and e2e scenario is run with the new images

### CODE REVIEW

**Review by amitkrout — APPROVED** [review]
LGTM
```
$ git grep "redhat-developer"
$
```

**Review by amitkrout — CHANGES_REQUESTED** [review]
@kadel Seems flag ```--wait``` is not supported in ```oc 3.10.0```
```
Running command: oc delete project odo-source --wait --now
Error: unknown flag: --wait
[...]
```

Can you please update the oc binary version to ```3.11.0``` in https://github.com/openshift/odo-supervisord-image/blob/master/scripts/oc-cluster.sh#L21 and also update the remaining 3.10.0 reference to 3.11.0

For example: 
```
sudo wget https://github.com/openshift/origin/releases/download/v3.11.0/openshift-origin-client-tools-v3.11.0-0cbc58b-linux-64bit.tar.gz -O /tmp/openshift-origin-client-tools.tar.gz 2> /dev/null > /dev/nul
```

**Review by mohammedzee1000 — APPROVED** [review]
Makes sense, looking good
/approve

**Pull request merged**
