### PR TITLE
Remove deprecated Nodejs images

### PR DESCRIPTION
**Pull request by amitkrout**
Follow up of - https://github.com/openshift/odo/pull/3414

ping @girishramnani

### CODE REVIEW

**Comment by kadel** [comment]
There needs to be a matching PR on odo cli https://github.com/openshift/odo/blob/9a470629475bf6339dec637ee5ea8e326188a7fd/pkg/catalog/catalog.go#L460

**Comment by kadel** [comment]
ping @amitkrout

**Comment by amitkrout** [comment]
> There needs to be a matching PR on odo cli https://github.com/openshift/odo/blob/9a470629475bf6339dec637ee5ea8e326188a7fd/pkg/catalog/catalog.go#L460

Fixed via https://github.com/openshift/odo/pull/3587

**Comment by girishramnani** [comment]
Usually we push to a personal docker repo and use that in odo to confirm that tests pass. I hope u do that @amitkrout 
/approve

**Comment by amitkrout** [comment]
> Usually we push to a personal docker repo and use that in odo to confirm that tests pass. I hope u do that @amitkrout
> /approve

Travis script is handling this through https://github.com/openshift/odo-init-image/blob/master/scripts/build-push-image.sh

**Comment by amitkrout** [comment]
> > Usually we push to a personal docker repo and use that in odo to confirm that tests pass. I hope u do that @amitkrout
> > /approve
> 
> Travis script is handling this through https://github.com/openshift/odo-init-image/blob/master/scripts/build-push-image.sh

Ahh.. its commented https://github.com/openshift/odo-init-image/blob/master/.travis.yml#L19
/hold

**Comment by amitkrout** [comment]
https://github.com/openshift/odo-init-image/pull/72#issuecomment-702735657
/close

**Pull request closed without merging**
