### PR TITLE
Owner file cleanUp

### PR DESCRIPTION
**Pull request by amitkrout**
Owner file cleanup

### CODE REVIEW

**Review by mik-dass — APPROVED** [review]
/approve

**Comment by mik-dass** [comment]
@amitkrout Except `make test-generic` all other make targets seem to be failing, any idea why?

**Comment by amitkrout** [comment]
> @amitkrout Except `make test-generic` all other make targets seem to be failing, any idea why?

@mik-dass Because the make target has been changed and here travis job still uses the old target name. To fix this i have already created a separate pr #32.  

These failure will be fixed once pr #32 goes in.

**Pull request merged**
