### PR TITLE
Remanes devdebug to debugrun

### PR DESCRIPTION
**Pull request by mik-dass**
Renames for #https://github.com/openshift/odo/pull/3059/ to work

### CODE REVIEW

**Comment by amitkrout** [comment]
@mik-dass pr https://github.com/openshift/odo-init-image/pull/61 will fix the travis failure

**Comment by mik-dass** [comment]
@amitkrout I have rebased the PR as #61 is merged. Please have a look.

**Comment by amitkrout** [comment]
> @amitkrout I have rebased the PR as #61 is merged. Please have a look.

/lgtm

**Pull request merged**
